###
localhost:8080/flux

###
localhost:8080/flux-dto

###
localhost:8080/web-flux

###
localhost:8080/stream-sse-header

###
localhost:8080/stream-sse-header2


###
localhost:8080/stream-sse-header3


###
localhost:8080/stream-sse

###
localhost:8080/mvc/sse-emitter